[mgr]
prepend_keymap = [
	{ on  = "y", run = [ "shell --confirm 'for path in \"$@\"; do echo \"file://$path\"; done | wl-copy -t text/uri-list'", "yank" ] },
	{ on = "<C-q>", run = "quit" },
	{ on  = "<C-n>", run = 'shell -- dragon-drop -x -i -T "$0"' }
]
